import { mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'

import {
  condaSpecOf,
  condaSubdir,
  parseExplicitLock,
  type CondaDependency,
  type EnvironmentSpec,
  type PhiPlatform
} from './contract'
import { ensureMambarc, ensureRuntimeLayout, runMicromamba, type CondaOverrides } from './runtime'

/**
 * Oldest systems an official lock must support. Virtual-package overrides keep a lock
 * independent of the machine that solved it (a macOS host has no glibc, so a linux-64
 * cross-solve needs `glibc` set). glibc 2.17 matches the offline HPC clusters Phi targets.
 * Project solves do not use these: they solve the current platform with no CONDA_OVERRIDE_*.
 */
export const PLATFORM_BASELINES: Record<PhiPlatform, CondaOverrides> = {
  'linux-x64': { glibc: '2.17', linux: '4.18' },
  'darwin-arm64': { osx: '11.0' },
  'darwin-x64': { osx: '10.15' }
}

export function baselineLabel(platform: PhiPlatform): string {
  return Object.entries(PLATFORM_BASELINES[platform])
    .map(([key, value]) => `${key} ${value}`)
    .join(', ')
}

const SOLVE_ATTEMPTS = 3
const SOLVE_TIMEOUT_MS = 300_000

const MD5_HEX = /^[0-9a-fA-F]{32}$/

export interface ExplicitLockMeta {
  /** Spec path relative to the repo root, `/`-separated. */
  specPath: string
  platform: PhiPlatform
  /** conda subdir, for example `osx-arm64`. */
  subdir: string
  micromambaVersion: string
  /**
   * Baseline comment. Omit to use {@link baselineLabel}. `false` omits the line
   * (a project solve did not set CONDA_OVERRIDE_*).
   */
  baseline?: string | false
}

export interface SolveExplicitLockInput {
  root: string
  spec: EnvironmentSpec
  platform: PhiPlatform
  signal?: AbortSignal
  /** Set only for official cross-platform locks. Project solves omit this. */
  condaOverrides?: CondaOverrides
  /** `# spec:` header. Defaults to the spec name. */
  specPath?: string
  /** Retry notice. Official `lock-env` prints it; project solves stay quiet. */
  log?: (message: string) => void
}

interface LockedPackage {
  url: string
  md5: string
  /** Absent when the dry-run entry had no size, or FETCH and LINK disagreed. */
  size?: number
}

/** Union of dry-run `actions.FETCH` and `actions.LINK`, keyed by URL, as an `@EXPLICIT` lock. */
export function explicitLockFromDryRun(json: unknown, meta: ExplicitLockMeta): string {
  const packages = unionDryRunPackages(json)
  const lines = packages.map((pkg) => `${pkg.url}#${pkg.md5}`)
  const baseline =
    meta.baseline === false ? undefined : (meta.baseline ?? baselineLabel(meta.platform))
  const header = [
    '# Generated by scripts/runtime/lock-env.ts \u2014 do not edit by hand.',
    `# spec: ${meta.specPath}`,
    `# platform: ${meta.platform} (${meta.subdir})`,
    `# micromamba: ${meta.micromambaVersion}`
  ]
  if (baseline !== undefined) header.push(`# baseline: ${baseline}`)
  const bytes = totalDownloadBytes(packages)
  if (baseline === undefined && bytes !== undefined) {
    header.push(`# download-bytes: ${String(bytes)}`)
  }
  const text = [...header, '@EXPLICIT', ...lines, ''].join('\n')
  if (baseline === undefined || bytes === undefined) return text
  return withDownloadBytes(text, bytes)
}

/** Explicit locks cannot record pip dependencies. Throws when any are present. */
export function refusePipDependencies(dependencies: readonly CondaDependency[]): void {
  const pip = dependencies.filter((dependency) => typeof dependency !== 'string')
  if (pip.length === 0) return
  const packages = pip.flatMap((dependency) => dependency.pip)
  const detail = packages.length > 0 ? ` (${packages.join(', ')})` : ''
  throw new Error(`explicit locks cannot express pip: dependencies${detail}`)
}

/**
 * Dry-run solve plus an `@EXPLICIT` lock, including `# download-bytes:` when the
 * solver reported sizes. `condaOverrides` is forwarded only when the caller sets it.
 */
export async function solveExplicitLock(input: SolveExplicitLockInput): Promise<string> {
  const conda = condaSpecOf(input.spec)
  refusePipDependencies(conda.dependencies)
  const specs = conda.dependencies.filter(
    (dependency): dependency is string => typeof dependency === 'string'
  )
  if (input.signal?.aborted) throw abortError()
  ensureRuntimeLayout(input.root)
  ensureMambarc(input.root)
  const micromambaVersion = await readMicromambaVersion(input.root, input.signal)
  const strictChannelPriority = await supportsStrictChannelPriority(input.root, input.signal)
  const prefix = mkdtempSync(join(input.root, 'state', 'solve-'))
  try {
    const json = await solveDryRun(
      input.root,
      solveArgs({
        platform: input.platform,
        channels: conda.channels,
        specs,
        prefix,
        strictChannelPriority
      }),
      input.platform,
      input.signal,
      input.condaOverrides,
      input.log
    )
    const text = explicitLockFromDryRun(json, {
      specPath: input.specPath ?? input.spec.name,
      platform: input.platform,
      subdir: condaSubdir(input.platform),
      micromambaVersion,
      ...(input.condaOverrides ? {} : { baseline: false as const })
    })
    const validated = parseExplicitLock(text)
    if (!validated.ok) {
      throw new Error(`generated lock is invalid: ${validated.errors.join('; ')}`)
    }
    if (input.condaOverrides === undefined && !text.includes('# download-bytes:')) {
      throw new Error('dry-run did not report download sizes')
    }
    return text
  } finally {
    rmSync(prefix, { recursive: true, force: true })
  }
}

/** Insert or replace `# download-bytes:` after `# baseline:` without changing any other line. */
export function withDownloadBytes(text: string, bytes: number): string {
  if (!Number.isSafeInteger(bytes) || bytes < 0) {
    throw new Error(`download-bytes must be a non-negative safe integer, got ${String(bytes)}`)
  }
  const line = `# download-bytes: ${String(bytes)}`
  const existing = /^# download-bytes: \d+/m.exec(text)
  if (existing) {
    return text.slice(0, existing.index) + line + text.slice(existing.index + existing[0].length)
  }
  const baseline = /^# baseline:[^\r\n]*/m.exec(text)
  if (!baseline) throw new Error('lock is missing a # baseline: line')
  const insertAt = baseline.index + baseline[0].length
  const newline = text.includes('\r\n') ? '\r\n' : '\n'
  return text.slice(0, insertAt) + newline + line + text.slice(insertAt)
}

interface SizeAccumulator {
  md5: string
  size?: number
  /** FETCH and LINK reported different sizes; the package then has no size. */
  conflict: boolean
}

function unionDryRunPackages(json: unknown): LockedPackage[] {
  if (!isRecord(json)) throw new Error('dry-run JSON must be an object')
  const actions = json.actions
  if (!isRecord(actions)) throw new Error('dry-run JSON is missing actions')

  const byUrl = new Map<string, SizeAccumulator>()
  for (const key of ['FETCH', 'LINK'] as const) {
    const group = actions[key]
    if (group == null) continue
    if (!Array.isArray(group)) throw new Error(`dry-run actions.${key} must be an array`)
    for (const entry of group) {
      const locked = lockPackage(entry)
      const previous = byUrl.get(locked.url)
      if (!previous) {
        byUrl.set(locked.url, { md5: locked.md5, size: locked.size, conflict: false })
        continue
      }
      if (previous.md5 !== locked.md5) {
        throw new Error(`dry-run package ${locked.url} has conflicting md5 values`)
      }
      notePackageSize(previous, locked.size)
    }
  }
  if (byUrl.size === 0) throw new Error('dry-run produced no packages')

  return [...byUrl.entries()]
    .sort((left, right) => (left[0] < right[0] ? -1 : left[0] > right[0] ? 1 : 0))
    .map(([url, locked]) => ({
      url,
      md5: locked.md5,
      ...(locked.conflict || locked.size === undefined ? {} : { size: locked.size })
    }))
}

function notePackageSize(current: SizeAccumulator, size: number | undefined): void {
  if (current.conflict || size === undefined) return
  if (current.size === undefined) {
    current.size = size
    return
  }
  if (current.size !== size) {
    current.conflict = true
    current.size = undefined
  }
}

function lockPackage(entry: unknown): LockedPackage {
  if (!isRecord(entry)) throw new Error('dry-run package entry must be an object')
  const label = packageLabel(entry)
  const url = entry.url
  if (
    typeof url !== 'string' ||
    !url.startsWith('https://') ||
    /\s/.test(url) ||
    url.includes('#')
  ) {
    throw new Error(`dry-run package ${label} URL must use https`)
  }
  const md5 = entry.md5
  if (typeof md5 !== 'string' || !MD5_HEX.test(md5)) {
    throw new Error(`dry-run package ${label} is missing a 32-hex md5`)
  }
  return { url, md5: md5.toLowerCase(), size: readPackageSize(entry.size) }
}

function readPackageSize(value: unknown): number | undefined {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) return undefined
  return value
}

function totalDownloadBytes(packages: readonly LockedPackage[]): number | undefined {
  let total = 0
  for (const pkg of packages) {
    if (pkg.size === undefined) return undefined
    total += pkg.size
    if (!Number.isSafeInteger(total)) return undefined
  }
  return total
}

function packageLabel(entry: Record<string, unknown>): string {
  const name = typeof entry.name === 'string' ? entry.name : 'package'
  const version = typeof entry.version === 'string' ? entry.version : ''
  return version.length > 0 ? `${name}-${version}` : name
}

interface SolveArgInput {
  platform: PhiPlatform
  channels: readonly string[]
  specs: readonly string[]
  prefix: string
  strictChannelPriority: boolean
}

function solveArgs(input: SolveArgInput): string[] {
  const args = [
    'create',
    '--dry-run',
    '--json',
    '--platform',
    condaSubdir(input.platform),
    '-p',
    input.prefix,
    '--override-channels'
  ]
  for (const channel of input.channels) args.push('-c', channel)
  if (input.strictChannelPriority) args.push('--strict-channel-priority')
  args.push(...input.specs)
  return args
}

async function solveDryRun(
  root: string,
  args: readonly string[],
  platform: PhiPlatform,
  signal: AbortSignal | undefined,
  condaOverrides: CondaOverrides | undefined,
  log: ((message: string) => void) | undefined
): Promise<unknown> {
  let lastError = `micromamba solve produced no error text for ${platform}`
  for (let attempt = 1; attempt <= SOLVE_ATTEMPTS; attempt += 1) {
    if (signal?.aborted) throw abortError()
    const result = await runMicromamba(args, {
      root,
      timeoutMs: SOLVE_TIMEOUT_MS,
      signal,
      ...(condaOverrides ? { condaOverrides } : {})
    })
    if (signal?.aborted) throw abortError()
    if (result.code === 0) {
      try {
        const json = parseSolverJson(result.stdout)
        if (isRecord(json) && json.success === false) {
          lastError = solverFailureText(result)
        } else {
          return json
        }
      } catch (error) {
        lastError = error instanceof Error ? error.message : String(error)
      }
    } else {
      lastError = solverFailureText(result)
    }
    if (attempt < SOLVE_ATTEMPTS) {
      log?.(`${platform}: solve attempt ${attempt} failed; retrying`)
      await delay(1000)
    }
  }
  throw new Error(`${platform}:\n${lastError}`)
}

function solverFailureText(result: {
  code: number | null
  stdout: string
  stderr: string
}): string {
  const parts = [result.stderr.trim(), result.stdout.trim()].filter((part) => part.length > 0)
  if (parts.length > 0) return parts.join('\n')
  if (result.code === null) return 'micromamba timed out'
  return `micromamba exited with code ${String(result.code)}`
}

function parseSolverJson(stdout: string): unknown {
  const trimmed = stdout.trim()
  if (trimmed.length === 0) throw new Error('micromamba dry-run returned empty output')
  try {
    return JSON.parse(trimmed) as unknown
  } catch {
    const start = trimmed.indexOf('{')
    const end = trimmed.lastIndexOf('}')
    if (start >= 0 && end > start) {
      try {
        return JSON.parse(trimmed.slice(start, end + 1)) as unknown
      } catch {
        // Fall through to the error below.
      }
    }
    throw new Error(`micromamba dry-run did not return JSON:\n${trimmed}`)
  }
}

async function readMicromambaVersion(
  root: string,
  signal: AbortSignal | undefined
): Promise<string> {
  const result = await runMicromamba(['--version'], { root, signal })
  if (signal?.aborted) throw abortError()
  if (result.code !== 0) throw new Error(solverFailureText(result))
  const version = result.stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .find((line) => line.length > 0)
  if (!version) throw new Error('micromamba --version returned no version')
  return version
}

async function supportsStrictChannelPriority(
  root: string,
  signal: AbortSignal | undefined
): Promise<boolean> {
  const result = await runMicromamba(['create', '--help'], { root, signal })
  if (signal?.aborted) throw abortError()
  return `${result.stdout}\n${result.stderr}`.includes('--strict-channel-priority')
}

function delay(ms: number): Promise<void> {
  return new Promise((resolveDelay) => {
    setTimeout(resolveDelay, ms)
  })
}

function abortError(): Error {
  const error = new Error('aborted')
  error.name = 'AbortError'
  return error
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
