// Turns an environment.yml into one explicit lock per platform.
//
// Usage (needs the TS loader, so go through the npm script):
//   npm run runtime:lock -- --spec tests/fixtures/envs/minimal/environment.yml
//   npm run runtime:lock -- --spec environment.yml --out builds/locks
//   npm run runtime:lock -- --spec environment.yml --platform darwin-arm64 linux-x64
//   npm run runtime:lock -- --annotate path/to/lock.txt …

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  PHI_PLATFORMS,
  condaSpecOf,
  condaSubdir,
  lockSha256,
  parseEnvironmentSpec,
  parseExplicitLock,
  parseLockDownloadBytes,
  type CondaDependency,
  type PhiPlatform
} from '../../src/main/agent/envs/contract'
import {
  ensureRuntimeLayout,
  runMicromamba,
  writeMambarc,
  type CondaOverrides
} from '../../src/main/agent/envs/runtime'

/**
 * Oldest systems a lock must support, used as virtual-package overrides so a lock does not
 * depend on the machine that solved it (and so a macOS host can solve linux-64 at all:
 * it has no glibc). glibc 2.17 matches the offline HPC clusters Phi targets.
 */
export const PLATFORM_BASELINES: Record<PhiPlatform, CondaOverrides> = {
  'linux-x64': { glibc: '2.17', linux: '4.18' },
  'darwin-arm64': { osx: '11.0' },
  'darwin-x64': { osx: '10.15' }
}

export function baselineLabel(platform: PhiPlatform): string {
  return Object.entries(PLATFORM_BASELINES[platform])
    .map(([key, value]) => `${key} ${value}`)
    .join(', ')
}

const SOLVE_ATTEMPTS = 3
const SOLVE_TIMEOUT_MS = 300_000

const MD5_HEX = /^[0-9a-fA-F]{32}$/

export interface ExplicitLockMeta {
  /** Spec path relative to the repo root, `/`-separated. */
  specPath: string
  platform: PhiPlatform
  /** conda subdir, for example `osx-arm64`. */
  subdir: string
  micromambaVersion: string
}

export interface LockEnvironmentOptions {
  specPath: string
  outDir?: string
  platforms?: readonly PhiPlatform[]
  /** Defaults to this repo (two levels above `scripts/runtime`). */
  repoRoot?: string
}

export interface LockSummary {
  platform: PhiPlatform
  packageCount: number
  lockSha256: string
  lockPath: string
}

interface LockedPackage {
  url: string
  md5: string
  /** Absent when the dry-run entry had no size, or FETCH and LINK disagreed. */
  size?: number
}

/** Union of dry-run `actions.FETCH` and `actions.LINK`, keyed by URL, as an `@EXPLICIT` lock. */
export function explicitLockFromDryRun(json: unknown, meta: ExplicitLockMeta): string {
  const packages = unionDryRunPackages(json)
  const lines = packages.map((pkg) => `${pkg.url}#${pkg.md5}`)
  const text = [
    '# Generated by scripts/runtime/lock-env.ts — do not edit by hand.',
    `# spec: ${meta.specPath}`,
    `# platform: ${meta.platform} (${meta.subdir})`,
    `# micromamba: ${meta.micromambaVersion}`,
    `# baseline: ${baselineLabel(meta.platform)}`,
    '@EXPLICIT',
    ...lines,
    ''
  ].join('\n')
  const bytes = totalDownloadBytes(packages)
  return bytes === undefined ? text : withDownloadBytes(text, bytes)
}

/** Explicit locks cannot record pip dependencies. Throws when any are present. */
export function refusePipDependencies(dependencies: readonly CondaDependency[]): void {
  const pip = dependencies.filter((dependency) => typeof dependency !== 'string')
  if (pip.length === 0) return
  const packages = pip.flatMap((dependency) => dependency.pip)
  const detail = packages.length > 0 ? ` (${packages.join(', ')})` : ''
  throw new Error(`explicit locks cannot express pip: dependencies${detail}`)
}

export async function lockEnvironment(options: LockEnvironmentOptions): Promise<LockSummary[]> {
  const repoRoot = options.repoRoot ?? defaultRepoRoot()
  const specPath = resolve(options.specPath)
  const parsed = parseEnvironmentSpec(readSpec(specPath))
  if (!parsed.ok) throw new Error(parsed.errors.join('\n'))

  const conda = condaSpecOf(parsed.spec)
  refusePipDependencies(conda.dependencies)
  const specs = conda.dependencies.filter(
    (dependency): dependency is string => typeof dependency === 'string'
  )
  const platforms = options.platforms ?? PHI_PLATFORMS
  const outDir = resolve(options.outDir ?? join(dirname(specPath), 'locks'))
  mkdirSync(outDir, { recursive: true })

  const root = mkdtempSync(join(tmpdir(), 'phi-lock-env-'))
  try {
    ensureRuntimeLayout(root)
    writeMambarc(root)
    const micromambaVersion = await readMicromambaVersion(root)
    const strictChannelPriority = await supportsStrictChannelPriority(root)
    const summaries: LockSummary[] = []
    for (const platform of platforms) {
      summaries.push(
        await lockPlatform({
          root,
          platform,
          channels: conda.channels,
          specs,
          prefix: join(root, 'envs', platform),
          outDir,
          specPath: repoRelative(specPath, repoRoot),
          micromambaVersion,
          strictChannelPriority
        })
      )
    }
    return summaries
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}

interface SizeAccumulator {
  md5: string
  size?: number
  /** FETCH and LINK reported different sizes; the package then has no size. */
  conflict: boolean
}

function unionDryRunPackages(json: unknown): LockedPackage[] {
  if (!isRecord(json)) throw new Error('dry-run JSON must be an object')
  const actions = json.actions
  if (!isRecord(actions)) throw new Error('dry-run JSON is missing actions')

  const byUrl = new Map<string, SizeAccumulator>()
  for (const key of ['FETCH', 'LINK'] as const) {
    const group = actions[key]
    if (group == null) continue
    if (!Array.isArray(group)) throw new Error(`dry-run actions.${key} must be an array`)
    for (const entry of group) {
      const locked = lockPackage(entry)
      const previous = byUrl.get(locked.url)
      if (!previous) {
        byUrl.set(locked.url, { md5: locked.md5, size: locked.size, conflict: false })
        continue
      }
      if (previous.md5 !== locked.md5) {
        throw new Error(`dry-run package ${locked.url} has conflicting md5 values`)
      }
      notePackageSize(previous, locked.size)
    }
  }
  if (byUrl.size === 0) throw new Error('dry-run produced no packages')

  return [...byUrl.entries()]
    .sort((left, right) => (left[0] < right[0] ? -1 : left[0] > right[0] ? 1 : 0))
    .map(([url, locked]) => ({
      url,
      md5: locked.md5,
      ...(locked.conflict || locked.size === undefined ? {} : { size: locked.size })
    }))
}

function notePackageSize(current: SizeAccumulator, size: number | undefined): void {
  if (current.conflict || size === undefined) return
  if (current.size === undefined) {
    current.size = size
    return
  }
  if (current.size !== size) {
    current.conflict = true
    current.size = undefined
  }
}

function lockPackage(entry: unknown): LockedPackage {
  if (!isRecord(entry)) throw new Error('dry-run package entry must be an object')
  const label = packageLabel(entry)
  const url = entry.url
  if (
    typeof url !== 'string' ||
    !url.startsWith('https://') ||
    /\s/.test(url) ||
    url.includes('#')
  ) {
    throw new Error(`dry-run package ${label} URL must use https`)
  }
  const md5 = entry.md5
  if (typeof md5 !== 'string' || !MD5_HEX.test(md5)) {
    throw new Error(`dry-run package ${label} is missing a 32-hex md5`)
  }
  return { url, md5: md5.toLowerCase(), size: readPackageSize(entry.size) }
}

function readPackageSize(value: unknown): number | undefined {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) return undefined
  return value
}

function totalDownloadBytes(packages: readonly LockedPackage[]): number | undefined {
  let total = 0
  for (const pkg of packages) {
    if (pkg.size === undefined) return undefined
    total += pkg.size
    if (!Number.isSafeInteger(total)) return undefined
  }
  return total
}

function packageLabel(entry: Record<string, unknown>): string {
  const name = typeof entry.name === 'string' ? entry.name : 'package'
  const version = typeof entry.version === 'string' ? entry.version : ''
  return version.length > 0 ? `${name}-${version}` : name
}

interface LockPlatformInput {
  root: string
  platform: PhiPlatform
  channels: readonly string[]
  specs: readonly string[]
  prefix: string
  outDir: string
  specPath: string
  micromambaVersion: string
  strictChannelPriority: boolean
}

async function lockPlatform(input: LockPlatformInput): Promise<LockSummary> {
  const json = await solveDryRun(input.root, solveArgs(input), input.platform)
  const text = explicitLockFromDryRun(json, {
    specPath: input.specPath,
    platform: input.platform,
    subdir: condaSubdir(input.platform),
    micromambaVersion: input.micromambaVersion
  })
  const validated = parseExplicitLock(text)
  if (!validated.ok) {
    throw new Error(`generated lock is invalid:\n${validated.errors.join('\n')}`)
  }
  const lockPath = join(input.outDir, `${input.platform}.txt`)
  writeFileSync(lockPath, text, 'utf8')
  return {
    platform: input.platform,
    packageCount: validated.entries.length,
    lockSha256: lockSha256(text),
    lockPath
  }
}

function solveArgs(input: LockPlatformInput): string[] {
  const args = [
    'create',
    '--dry-run',
    '--json',
    '--platform',
    condaSubdir(input.platform),
    '-p',
    input.prefix,
    '--override-channels'
  ]
  for (const channel of input.channels) args.push('-c', channel)
  if (input.strictChannelPriority) args.push('--strict-channel-priority')
  args.push(...input.specs)
  return args
}

async function solveDryRun(
  root: string,
  args: readonly string[],
  platform: PhiPlatform
): Promise<unknown> {
  let lastError = `micromamba solve produced no error text for ${platform}`
  for (let attempt = 1; attempt <= SOLVE_ATTEMPTS; attempt += 1) {
    const result = await runMicromamba(args, {
      root,
      timeoutMs: SOLVE_TIMEOUT_MS,
      condaOverrides: PLATFORM_BASELINES[platform]
    })
    if (result.code === 0) {
      try {
        const json = parseSolverJson(result.stdout)
        if (isRecord(json) && json.success === false) {
          lastError = solverFailureText(result)
        } else {
          return json
        }
      } catch (error) {
        lastError = error instanceof Error ? error.message : String(error)
      }
    } else {
      lastError = solverFailureText(result)
    }
    if (attempt < SOLVE_ATTEMPTS) {
      console.error(`${platform}: solve attempt ${attempt} failed; retrying`)
      await delay(1000)
    }
  }
  throw new Error(`${platform}:\n${lastError}`)
}

function solverFailureText(result: {
  code: number | null
  stdout: string
  stderr: string
}): string {
  const parts = [result.stderr.trim(), result.stdout.trim()].filter((part) => part.length > 0)
  if (parts.length > 0) return parts.join('\n')
  if (result.code === null) return 'micromamba timed out'
  return `micromamba exited with code ${String(result.code)}`
}

function parseSolverJson(stdout: string): unknown {
  const trimmed = stdout.trim()
  if (trimmed.length === 0) throw new Error('micromamba dry-run returned empty output')
  try {
    return JSON.parse(trimmed) as unknown
  } catch {
    const start = trimmed.indexOf('{')
    const end = trimmed.lastIndexOf('}')
    if (start >= 0 && end > start) {
      try {
        return JSON.parse(trimmed.slice(start, end + 1)) as unknown
      } catch {
        // Fall through to the error below.
      }
    }
    throw new Error(`micromamba dry-run did not return JSON:\n${trimmed}`)
  }
}

async function readMicromambaVersion(root: string): Promise<string> {
  const result = await runMicromamba(['--version'], { root })
  if (result.code !== 0) throw new Error(solverFailureText(result))
  const version = result.stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .find((line) => line.length > 0)
  if (!version) throw new Error('micromamba --version returned no version')
  return version
}

async function supportsStrictChannelPriority(root: string): Promise<boolean> {
  const result = await runMicromamba(['create', '--help'], { root })
  return `${result.stdout}\n${result.stderr}`.includes('--strict-channel-priority')
}

function readSpec(specPath: string): string {
  try {
    return readFileSync(specPath, 'utf8')
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    throw new Error(`failed to read environment spec ${specPath}: ${message}`)
  }
}

function repoRelative(specPath: string, repoRoot: string): string {
  return relative(repoRoot, specPath).split(sep).join('/')
}

function defaultRepoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), '../..')
}

function isPhiPlatform(value: string): value is PhiPlatform {
  for (const platform of PHI_PLATFORMS) {
    if (platform === value) return true
  }
  return false
}

const HEAD_ATTEMPTS = 3
const HEAD_CONCURRENCY = 16

export interface AnnotateLockOptions {
  fetch?: typeof fetch
  /** Defaults to 16. */
  concurrency?: number
  /** Sizes already known, keyed by the package URL without the md5 fragment. */
  cache?: Map<string, number>
  delay?: (ms: number) => Promise<void>
}

/** Insert or replace `# download-bytes:` after `# baseline:` without changing any other line. */
export function withDownloadBytes(text: string, bytes: number): string {
  if (!Number.isSafeInteger(bytes) || bytes < 0) {
    throw new Error(`download-bytes must be a non-negative safe integer, got ${String(bytes)}`)
  }
  const line = `# download-bytes: ${String(bytes)}`
  const existing = /^# download-bytes: \d+/m.exec(text)
  if (existing) {
    return text.slice(0, existing.index) + line + text.slice(existing.index + existing[0].length)
  }
  const baseline = /^# baseline:[^\r\n]*/m.exec(text)
  if (!baseline) throw new Error('lock is missing a # baseline: line')
  const insertAt = baseline.index + baseline[0].length
  const newline = text.includes('\r\n') ? '\r\n' : '\n'
  return text.slice(0, insertAt) + newline + line + text.slice(insertAt)
}

function downloadUrl(lockUrl: string): string {
  const hash = lockUrl.indexOf('#')
  return hash === -1 ? lockUrl : lockUrl.slice(0, hash)
}

async function mapLimited<T, R>(
  items: readonly T[],
  limit: number,
  run: (item: T) => Promise<R>
): Promise<R[]> {
  if (items.length === 0) return []
  const results = new Array<R>(items.length)
  let cursor = 0
  const workers = Math.max(1, Math.min(limit, items.length))
  async function worker(): Promise<void> {
    for (;;) {
      const index = cursor
      cursor += 1
      if (index >= items.length) return
      results[index] = await run(items[index] as T)
    }
  }
  await Promise.all(Array.from({ length: workers }, () => worker()))
  return results
}

async function headContentLength(
  url: string,
  fetchImpl: typeof fetch,
  wait: (ms: number) => Promise<void>
): Promise<number> {
  let lastError: unknown
  for (let attempt = 1; attempt <= HEAD_ATTEMPTS; attempt += 1) {
    try {
      const response = await fetchImpl(url, { method: 'HEAD', redirect: 'follow' })
      if (!response.ok) throw new Error(`HEAD ${url} returned ${String(response.status)}`)
      const header = response.headers.get('content-length')
      if (header === null || !/^[0-9]+$/.test(header)) {
        throw new Error(`HEAD ${url} did not return Content-Length`)
      }
      const bytes = Number(header)
      if (!Number.isSafeInteger(bytes)) {
        throw new Error(`HEAD ${url} returned an invalid Content-Length`)
      }
      return bytes
    } catch (error) {
      lastError = error
      if (attempt < HEAD_ATTEMPTS) await wait(200 * attempt)
    }
  }
  const message = lastError instanceof Error ? lastError.message : String(lastError)
  throw new Error(`failed to read Content-Length for ${url}: ${message}`)
}

/** HEAD every package URL and insert `# download-bytes:`. A missing size throws; nothing is guessed. */
export async function annotateLockText(
  text: string,
  options: AnnotateLockOptions = {}
): Promise<string> {
  const parsed = parseExplicitLock(text)
  if (!parsed.ok) throw new Error(parsed.errors.join('\n'))
  const fetchImpl = options.fetch ?? globalThis.fetch
  const wait = options.delay ?? delay
  const known = options.cache ?? new Map<string, number>()
  const urls = parsed.entries.map((entry) => downloadUrl(entry.url))
  const missing = [...new Set(urls)].filter((url) => !known.has(url))
  const fetched = await mapLimited(missing, options.concurrency ?? HEAD_CONCURRENCY, (url) =>
    headContentLength(url, fetchImpl, wait)
  )
  missing.forEach((url, index) => {
    const size = fetched[index]
    if (size === undefined) throw new Error(`missing size for ${url}`)
    known.set(url, size)
  })
  let total = 0
  for (const url of urls) {
    const size = known.get(url)
    if (size === undefined) throw new Error(`missing size for ${url}`)
    total += size
    if (!Number.isSafeInteger(total)) throw new Error('download size exceeds a safe integer')
  }
  return withDownloadBytes(text, total)
}

interface LockCliOptions {
  specPath?: string
  outDir?: string
  platforms: readonly PhiPlatform[]
  annotate: string[]
}

function parseArgs(argv: readonly string[]): LockCliOptions {
  let specPath: string | undefined
  let outDir: string | undefined
  const platforms: PhiPlatform[] = []
  const annotate: string[] = []

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === '--spec') {
      specPath = requireValue(argv, index, '--spec requires an environment.yml path')
      index += 1
      continue
    }
    if (arg === '--out') {
      outDir = requireValue(argv, index, '--out requires a directory')
      index += 1
      continue
    }
    if (arg === '--platform') {
      const consumed = takePlatforms(argv, index, platforms)
      if (consumed === 0) throw new Error('--platform requires a platform id')
      index += consumed
      continue
    }
    if (arg === '--annotate') {
      const consumed = takeAnnotatePaths(argv, index, annotate)
      if (consumed === 0) throw new Error('--annotate requires a lock path')
      index += consumed
      continue
    }
    throw new Error(`unknown argument ${arg}`)
  }

  if (annotate.length > 0 && (specPath || outDir || platforms.length > 0)) {
    throw new Error('--annotate cannot be combined with --spec, --out, or --platform')
  }
  if (annotate.length === 0 && !specPath) {
    throw new Error(
      'usage: lock-env.ts --spec <environment.yml> [--out <dir>] [--platform <id> ...] | --annotate <lock.txt> ...'
    )
  }
  return {
    specPath,
    outDir,
    platforms: platforms.length > 0 ? platforms : PHI_PLATFORMS,
    annotate
  }
}

function requireValue(argv: readonly string[], index: number, message: string): string {
  const value = argv[index + 1]
  if (!value || value.startsWith('--')) throw new Error(message)
  return value
}

function takePlatforms(argv: readonly string[], index: number, platforms: PhiPlatform[]): number {
  let consumed = 0
  while (index + 1 + consumed < argv.length) {
    const value = argv[index + 1 + consumed]
    if (!value || value.startsWith('--')) break
    if (!isPhiPlatform(value)) {
      throw new Error(`unknown platform: ${value} (expected ${PHI_PLATFORMS.join(', ')})`)
    }
    if (!platforms.includes(value)) platforms.push(value)
    consumed += 1
  }
  return consumed
}

function takeAnnotatePaths(argv: readonly string[], index: number, paths: string[]): number {
  let consumed = 0
  while (index + 1 + consumed < argv.length) {
    const value = argv[index + 1 + consumed]
    if (!value || value.startsWith('--')) break
    paths.push(value)
    consumed += 1
  }
  return consumed
}

function delay(ms: number): Promise<void> {
  return new Promise((resolveDelay) => {
    setTimeout(resolveDelay, ms)
  })
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

async function annotateLocks(paths: readonly string[]): Promise<void> {
  const cache = new Map<string, number>()
  for (const lockPath of paths) {
    const absolute = resolve(lockPath)
    const text = readFileSync(absolute, 'utf8')
    const next = await annotateLockText(text, { cache })
    if (next !== text) writeFileSync(absolute, next, 'utf8')
    const bytes = parseLockDownloadBytes(next)
    const parsed = parseExplicitLock(next)
    const count = parsed.ok ? parsed.entries.length : 0
    console.log(
      `${lockPath}: ${count} packages, download-bytes ${bytes === undefined ? 'unknown' : String(bytes)}`
    )
  }
}

async function main(): Promise<void> {
  try {
    const options = parseArgs(process.argv.slice(2))
    if (options.annotate.length > 0) {
      await annotateLocks(options.annotate)
      return
    }
    if (!options.specPath) throw new Error('--spec requires an environment.yml path')
    const summaries = await lockEnvironment({
      specPath: options.specPath,
      ...(options.outDir ? { outDir: options.outDir } : {}),
      platforms: options.platforms
    })
    for (const summary of summaries) {
      console.log(
        `${summary.platform}: ${summary.packageCount} packages, lockSha256 ${summary.lockSha256.slice(0, 12)}`
      )
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}

const entry = process.argv[1]
if (entry && resolve(entry) === fileURLToPath(import.meta.url)) {
  void main()
}
