import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test, { type TestContext } from 'node:test'

import { PHI_PLATFORMS, parseExplicitLock } from '../src/main/agent/envs'
import { getMicromambaPath } from '../src/main/agent/envs/paths'
import { findPlatform } from '../src/main/agent/envs/platform'
import {
  PLATFORM_BASELINES,
  baselineLabel,
  explicitLockFromDryRun,
  lockEnvironment,
  refusePipDependencies,
  type ExplicitLockMeta
} from '../scripts/runtime/lock-env'

const repoRoot = process.cwd()
const fixtureSpec = join(repoRoot, 'tests/fixtures/envs/minimal/environment.yml')
const fixtureLocks = join(repoRoot, 'tests/fixtures/envs/minimal/locks')

const MD5_A = '0123456789abcdef0123456789abcdef'
const MD5_B = 'abcdef0123456789abcdef0123456789'
const MD5_C = 'fedcba9876543210fedcba9876543210'
const URL_CA = 'https://conda.anaconda.org/conda-forge/osx-arm64/ca-certificates-2026-h0.conda'
const URL_PYTHON = 'https://conda.anaconda.org/conda-forge/osx-arm64/python-3.12.0-h0.conda'
const URL_ZLIB = 'https://conda.anaconda.org/conda-forge/osx-arm64/zlib-1.3-h0.conda'

const meta: ExplicitLockMeta = {
  specPath: 'tests/fixtures/envs/minimal/environment.yml',
  platform: 'darwin-arm64',
  subdir: 'osx-arm64',
  micromambaVersion: '2.9.0'
}

function integrationSkip(): string | false {
  if (process.env.PHI_RUNTIME_INTEGRATION !== '1') {
    return 'network integration: set PHI_RUNTIME_INTEGRATION=1 (npm run test:runtime)'
  }
  if (process.env.PHI_OFFLINE === '1') return 'PHI_OFFLINE=1'
  try {
    getMicromambaPath()
    return false
  } catch (error) {
    return error instanceof Error ? error.message : String(error)
  }
}

const skipIntegration = integrationSkip()

function pkg(url: string, md5: string, name: string): Record<string, string> {
  return {
    url,
    md5,
    name,
    version: '1',
    subdir: 'osx-arm64',
    channel: 'conda-forge'
  }
}

function hasPython312(urls: readonly string[]): boolean {
  return urls.some((url) => /\/python-3\.12\./.test(url))
}

test('explicitLockFromDryRun unions FETCH and LINK, dedupes, and sorts', () => {
  const text = explicitLockFromDryRun(
    {
      actions: {
        FETCH: [pkg(URL_ZLIB, MD5_B, 'zlib'), pkg(URL_PYTHON, MD5_A, 'python')],
        LINK: [pkg(URL_PYTHON, MD5_A, 'python'), pkg(URL_CA, MD5_C, 'ca-certificates')]
      }
    },
    meta
  )
  assert.equal(
    text,
    [
      '# Generated by scripts/runtime/lock-env.ts — do not edit by hand.',
      '# spec: tests/fixtures/envs/minimal/environment.yml',
      '# platform: darwin-arm64 (osx-arm64)',
      '# micromamba: 2.9.0',
      '# baseline: osx 11.0',
      '@EXPLICIT',
      `${URL_CA}#${MD5_C}`,
      `${URL_PYTHON}#${MD5_A}`,
      `${URL_ZLIB}#${MD5_B}`,
      ''
    ].join('\n')
  )
  const parsed = parseExplicitLock(text)
  assert.equal(parsed.ok, true)
  if (!parsed.ok) return
  assert.equal(parsed.entries.length, 3)

  assert.throws(
    () =>
      explicitLockFromDryRun(
        {
          actions: {
            FETCH: [
              {
                url: URL_PYTHON,
                name: 'python',
                version: '3.12.0',
                subdir: 'osx-arm64',
                channel: 'conda-forge'
              }
            ]
          }
        },
        meta
      ),
    /md5/
  )
  assert.throws(
    () =>
      explicitLockFromDryRun(
        {
          actions: {
            LINK: [
              {
                url: 'http://example.com/python.conda',
                md5: MD5_A,
                name: 'python',
                version: '3.12.0',
                subdir: 'osx-arm64',
                channel: 'conda-forge'
              }
            ]
          }
        },
        meta
      ),
    /https/
  )
})

test('committed minimal locks parse and pin python 3.12', () => {
  for (const platform of PHI_PLATFORMS) {
    const text = readFileSync(join(fixtureLocks, `${platform}.txt`), 'utf8')
    assert.match(text, /^# Generated by scripts\/runtime\/lock-env\.ts — do not edit by hand\.\n/)
    assert.match(text, /^# spec: tests\/fixtures\/envs\/minimal\/environment\.yml$/m)
    assert.match(text, new RegExp(`^# platform: ${platform} \\(`, 'm'))
    const parsed = parseExplicitLock(text)
    assert.equal(parsed.ok, true)
    if (!parsed.ok) return
    assert.ok(hasPython312(parsed.entries.map((entry) => entry.url)), `${platform} lock`)
  }
})

test('pip dependencies are refused', () => {
  assert.throws(
    () => refusePipDependencies(['python=3.12', { pip: ['numpy==2.1.0'] }]),
    /explicit locks cannot express pip: dependencies/
  )
  assert.doesNotThrow(() => refusePipDependencies(['python=3.12']))
})

test(
  'locking the minimal fixture matches the committed package set for this platform',
  { skip: skipIntegration, timeout: 900_000 },
  async (t: TestContext) => {
    const platform = findPlatform()
    if (!platform) throw new Error(`unsupported platform: ${process.platform}-${process.arch}`)
    const outDir = mkdtempSync(join(tmpdir(), 'phi-lock-test-'))
    try {
      await lockEnvironment({
        specPath: fixtureSpec,
        outDir,
        platforms: [platform],
        repoRoot
      })
      const fresh = readFileSync(join(outDir, `${platform}.txt`), 'utf8')
      const committed = readFileSync(join(fixtureLocks, `${platform}.txt`), 'utf8')
      const freshParsed = parseExplicitLock(fresh)
      const committedParsed = parseExplicitLock(committed)
      assert.equal(freshParsed.ok, true)
      assert.equal(committedParsed.ok, true)
      if (!freshParsed.ok || !committedParsed.ok) return
      const freshUrls = freshParsed.entries.map((entry) => entry.url).sort()
      const committedUrls = committedParsed.entries.map((entry) => entry.url).sort()
      assert.equal(hasPython312(freshUrls), true)
      assert.equal(hasPython312(committedUrls), true)
      if (freshUrls.join('\n') !== committedUrls.join('\n')) {
        // The solver may select newer builds than the committed lock. When the
        // sets differ, require python 3.12 on both sides and report the diff.
        const onlyFresh = freshUrls.filter((url) => !committedUrls.includes(url))
        const onlyCommitted = committedUrls.filter((url) => !freshUrls.includes(url))
        t.diagnostic(
          `package set differs from the committed ${platform} lock\n` +
            `only in fresh solve:\n${onlyFresh.join('\n')}\n` +
            `only in committed lock:\n${onlyCommitted.join('\n')}`
        )
        return
      }
      assert.deepEqual(freshUrls, committedUrls)
    } finally {
      rmSync(outDir, { recursive: true, force: true })
    }
  }
)

test('every platform has a solve baseline and linux targets glibc 2.17', () => {
  assert.deepEqual(Object.keys(PLATFORM_BASELINES).sort(), [
    'darwin-arm64',
    'darwin-x64',
    'linux-x64'
  ])
  assert.equal(PLATFORM_BASELINES['linux-x64'].glibc, '2.17')
  assert.equal(baselineLabel('linux-x64'), 'glibc 2.17, linux 4.18')
})
