// SearXNG searx/settings.yml snapshot, retrieved 2026-09-30.
// Source: https://github.com/searxng/searxng/blob/master/searx/settings.yml
// Tuple: [name, shortcut, disabled by default, inactive on the default instance].
export type SearxngUpstreamEngine = [string, string | null, boolean, boolean]

export const SEARXNG_UPSTREAM_ENGINES: SearxngUpstreamEngine[] = [
  ['360search', '360so', true, false],
  ['360search videos', '360sov', true, false],
  ['500px', '500', false, false],
  ['9gag', '9g', true, false],
  ['abcnyheter', 'abc', true, false],
  ['acfun', 'acf', true, false],
  ['astrophysics data system', 'ads', false, true],
  ['alpine linux packages', 'alp', true, false],
  ['annas archive', 'aa', true, false],
  ['ansa', 'ans', true, false],
  ['apk mirror', 'apkm', true, false],
  ['apple app store', 'aps', true, false],
  ['ahmia', 'ah', false, false],
  ['anaconda', 'conda', true, false],
  ['arch linux wiki', 'al', false, false],
  ['nixos wiki', 'nixw', true, false],
  ['artic', 'arc', true, false],
  ['artstation', 'as', true, false],
  ['arxiv', 'arx', false, false],
  ['avalw', 'av', true, true],
  ['ayo', 'ayo', true, false],
  ['azure', 'az', false, true],
  ['bandcamp', 'bc', false, false],
  ['baidu', 'bd', true, false],
  ['baidu images', 'bdi', true, false],
  ['baidu kaifa', 'bdk', true, false],
  ['wikipedia', 'wp', false, false],
  ['bilibili', 'bil', true, false],
  ['bing', 'bi', true, false],
  ['bing images', 'bii', false, false],
  ['bing news', 'bin', false, false],
  ['bing videos', 'biv', false, false],
  ['bitchute', 'bit', true, false],
  ['bitbucket', 'bb', true, false],
  ['boardreader', 'boa', true, false],
  ['bpb', 'bpb', true, false],
  ['btdigg', 'bt', true, false],
  ['openverse', 'opv', true, false],
  ['media.ccc.de', 'c3tv', true, false],
  ['cachy os packages', 'cos', true, false],
  ['chefkoch', 'chef', false, false],
  ['chinaso news', 'chinaso', true, true],
  ['cl0q', 'cl', true, true],
  ['cloudflareai', 'cfai', false, true],
  ['core.ac.uk', 'cor', false, true],
  ['crossref', 'cr', true, false],
  ['crowdview', 'cv', true, false],
  ['yep', 'yep', true, false],
  ['currency', 'cc', false, false],
  ['deezer', 'dz', true, false],
  ['destatis', 'destat', true, false],
  ['deviantart', 'da', false, true],
  ['devicons', 'di', true, false],
  ['ddg definitions', 'ddd', true, false],
  ['docker hub', 'dh', false, false],
  ['encyclosearch', 'es', true, false],
  ['europepmc', 'epmc', false, false],
  ['erowid', 'ew', true, false],
  ['elasticsearch', 'els', false, true],
  ['wikidata', 'wd', false, false],
  ['dogpile', 'dog', false, true],
  ['dogpile images', 'dogi', false, true],
  ['dogpile videos', 'dogv', false, true],
  ['dogpile news', 'dogn', false, true],
  ['duckduckgo', 'ddg', false, false],
  ['duckduckgo web', 'ddgw', true, false],
  ['duckduckgo images', 'ddi', false, false],
  ['duckduckgo videos', 'ddv', false, false],
  ['duckduckgo news', 'ddn', false, false],
  ['duckduckgo weather', 'ddw', true, false],
  ['apple maps', 'apm', true, false],
  ['emojipedia', 'em', true, false],
  ['tineye', 'tin', true, false],
  ['etymonline', 'et', false, false],
  ['ebay', 'eb', false, true],
  ['1x', '1x', false, false],
  ['fastbot', 'fa', true, false],
  ['fdroid', 'fd', true, false],
  ['findborg', 'fi', false, true],
  ['findborg images', 'fii', false, true],
  ['findborg videos', 'fiv', false, true],
  ['findborg news', 'fin', false, true],
  ['findfiles', 'fif', true, false],
  ['findfiles images', 'fifi', true, false],
  ['findfiles videos', 'fifv', true, false],
  ['findfiles music', 'fifm', true, false],
  ['findthatmeme', 'ftm', true, false],
  ['fireball', 'fire', true, false],
  ['fireball news', 'firen', true, false],
  ['fireball videos', 'firev', true, false],
  ['flaticon', 'fli', true, false],
  ['flickr', 'fl', true, false],
  ['flickr_api', 'fla', false, true],
  ['free software directory', 'fsd', true, false],
  ['freesound', 'fnd', false, true],
  ['frinkiac', 'frk', true, false],
  ['fynd', 'fynd', true, false],
  ['fyyd', 'fy', true, false],
  ['gabanza', 'gab', true, false],
  ['geizhals', 'geiz', true, false],
  ['genius', 'gen', false, false],
  ['gentoo', 'ge', false, false],
  ['giphy', 'gif', true, false],
  ['gitlab', 'gl', true, false],
  ['github', 'gh', false, false],
  ['github code', 'ghc', false, true],
  ['codeberg', 'cb', true, false],
  ['gitea.com', 'gitea', true, false],
  ['gmx', 'gmx', true, false],
  ['goodreads', 'good', true, false],
  ['google', 'go', true, false],
  ['google images', 'goi', true, false],
  ['google news', 'gon', false, false],
  ['google videos', 'gov', false, false],
  ['google cse', 'goc', false, false],
  ['google cse images', 'goci', false, false],
  ['google scholar', 'gos', false, false],
  ['google play apps', 'gpa', true, false],
  ['google play movies', 'gpm', true, false],
  ['grokipedia', 'gp', true, true],
  ['material icons', 'mi', true, false],
  ['habrahabr', 'habr', true, false],
  ['hackernews', 'hn', true, false],
  ['hex', 'hex', true, false],
  ['crates.io', 'crates', true, false],
  ['hoogle', 'ho', false, false],
  ['iconify', 'ico', true, false],
  ['iseek', 'isk', true, true],
  ['il post', 'pst', true, false],
  ['huggingface', 'hf', true, false],
  ['huggingface datasets', 'hfd', true, false],
  ['huggingface spaces', 'hfs', true, false],
  ['imdb', 'imdb', true, false],
  ['imgur', 'img', true, false],
  ['ina', 'in', true, false],
  ['ipernity', 'ip', true, false],
  ['iqiyi', 'iq', true, false],
  ['jina', 'ji', false, true],
  ['kavunka demo', 'kav', true, true],
  ['keenable', 'keen', true, true],
  ['kozmonavt', 'koz', true, true],
  ['jisho', 'js', true, false],
  ['kickass', 'kc', false, false],
  ['kukei', 'kuk', true, true],
  ['lemmy communities', 'leco', false, false],
  ['lemmy users', 'leus', false, false],
  ['lemmy posts', 'lepo', false, false],
  ['lemmy comments', 'lecom', false, false],
  ['library genesis', 'lg', true, false],
  ['z-library', 'zlib', true, true],
  ['libretranslate', 'lt', false, true],
  ['littlelayer', 'll', true, true],
  ['lingva', 'lv', false, false],
  ['lobste.rs', 'lo', true, false],
  ['lucide', 'luc', true, false],
  ['luxxle', 'lux', true, true],
  ['luxxle images', 'luxi', true, true],
  ['luxxle videos', 'luxv', true, true],
  ['luxxle news', 'luxn', true, true],
  ['magnific', 'mag', true, false],
  ['marginalia', 'mar', true, true],
  ['mastodon users', 'mau', false, false],
  ['mastodon hashtags', 'mah', false, false],
  ['mdn', 'mdn', false, false],
  ['metacpan', 'cpan', true, false],
  ['microsoft learn', 'msl', true, false],
  ['mixcloud', 'mc', false, false],
  ['mozhi', 'mz', true, false],
  ['mwmbl', 'mwm', true, false],
  ['neocities', 'nc', true, true],
  ['niconico', 'nico', true, false],
  ['npm', 'npm', true, false],
  ['nyaa', 'nt', true, false],
  ['mankier', 'man', false, false],
  ['odysee', 'od', true, false],
  ['ollama', 'ollama', true, false],
  ['openairedatasets', 'oad', false, false],
  ['openairepublications', 'oap', false, false],
  ['openalex', 'oa', true, false],
  ['openclipart', 'ocl', true, true],
  ['openlibrary', 'ol', true, false],
  ['openmeteo', 'om', true, false],
  ['openstreetmap', 'osm', false, false],
  ['openrepos', 'or', true, false],
  ['packagist', 'pack', true, false],
  ['pdbe', 'pdb', false, false],
  ['pexels', 'pe', false, false],
  ['photon', 'ph', false, false],
  ['picjumbo', 'pj', false, false],
  ['pinterest', 'pin', false, false],
  ['piped', 'ppd', false, true],
  ['piped.music', 'ppdm', false, true],
  ['piratebay', 'tpb', false, false],
  ['pixabay images', 'pixi', true, false],
  ['pixabay videos', 'pixv', true, false],
  ['pixiv', 'pv', true, true],
  ['podchaser', 'poc', true, false],
  ['pub.dev', 'pd', true, false],
  ['public domain image archive', 'pdia', true, false],
  ['pubmed', 'pub', false, false],
  ['pypi', 'pypi', false, false],
  ['quark', 'qk', true, false],
  ['quark images', 'qki', true, false],
  ['qwant', 'qw', true, false],
  ['qwant news', 'qwn', true, false],
  ['qwant images', 'qwi', true, false],
  ['qwant videos', 'qwv', true, false],
  ['radio browser', 'rb', false, false],
  ['rawweb', 'rw', true, true],
  ['reuters', 'reu', false, false],
  ['rottentomatoes', 'rt', true, false],
  ['searchmysite', 'sms', true, false],
  ['searchrockit', 'sr', true, true],
  ['searchrockit images', 'sri', true, true],
  ['searchrockit news', 'srn', true, true],
  ['selfhst icons', 'si', true, false],
  ['sepiasearch', 'sep', false, false],
  ['shopify stock', 'shs', false, false],
  ['sogou', 'sogou', true, false],
  ['sogou images', 'sogoui', true, false],
  ['sogou videos', 'sogouv', true, false],
  ['sogou wechat', 'sogouw', true, false],
  ['soundcloud', 'sc', false, false],
  ['stackoverflow', 'st', false, false],
  ['stocksnap', 'sto', false, false],
  ['askubuntu', 'ubuntu', false, false],
  ['superuser', 'su', false, false],
  ['discuss.python', 'dpy', true, false],
  ['caddy.community', 'caddy', true, false],
  ['pi-hole.community', 'pi', true, false],
  ['privacywall', 'pw', true, false],
  ['privacywall images', 'pwi', true, false],
  ['privacywall videos', 'pwv', true, false],
  ['seekninja', 'sen', true, true],
  ['semantic scholar', 'se', false, false],
  ['springer nature', 'springer', false, true],
  ['startpage', 'sp', false, true],
  ['startpage news', 'spn', false, true],
  ['startpage images', 'spi', false, true],
  ['steam', 'stm', true, false],
  ['tokyotoshokan', 'tt', true, false],
  ['solidtorrents', 'solid', false, false],
  ['tagesschau', 'ts', true, false],
  ['tiger', 'tig', true, true],
  ['tiger news', 'tign', true, true],
  ['tmdb', 'tm', true, false],
  ['tonline', 'tol', true, true],
  ['tonline images', 'toli', true, true],
  ['tonline videos', 'tolv', true, true],
  ['tonline news', 'toln', true, true],
  ['torch', 'tch', false, false],
  ['Torznab EZTV', 'eztv', false, true],
  ['tusksearch', 'tu', true, false],
  ['tusksearch images', 'tui', true, false],
  ['tusksearch videos', 'tuv', true, false],
  ['tusksearch news', 'tun', true, false],
  ['unsplash', 'us', false, false],
  ['unobtanium', 'uno', true, true],
  ['yandex', 'yd', true, false],
  ['yandex images', 'ydi', true, false],
  ['yandex api', 'yda', false, true],
  ['yandex music', 'ydm', true, false],
  ['yahoo', 'yh', true, false],
  ['yahoo news', 'yhn', false, true],
  ['youtube', 'yt', false, false],
  ['youtube_api', 'yta', false, true],
  ['dailymotion', 'dm', false, false],
  ['vimeo', 'vm', false, false],
  ['wiby', 'wib', true, false],
  ['wikibooks', 'wb', true, false],
  ['wikinews', 'wn', false, false],
  ['wikiquote', 'wq', true, false],
  ['wikisource', 'ws', true, false],
  ['wikispecies', 'wsp', true, false],
  ['wiktionary', 'wt', false, false],
  ['wikiversity', 'wv', true, false],
  ['wikivoyage', 'wy', true, false],
  ['wikicommons.images', 'wci', false, false],
  ['wikicommons.videos', 'wcv', false, false],
  ['wikicommons.audio', 'wca', false, false],
  ['wikicommons.files', 'wcf', false, false],
  ['wolframalpha', 'wa', true, false],
  ['wolframalpha_api', 'waa', false, true],
  ['dictzone', 'dc', false, false],
  ['mymemory translated', 'tl', false, false],
  ['1337x', '1337x', true, false],
  ['duden', 'du', true, false],
  ['seznam', 'szn', true, false],
  ['deepl', 'dpl', false, true],
  ['mojeek', 'mjk', false, true],
  ['mojeek images', 'mjkimg', false, true],
  ['mojeek news', 'mjknews', false, true],
  ['moviepilot', 'mp', true, false],
  ['national vulnerability database', 'nvd', true, false],
  ['naver', 'nvr', true, false],
  ['naver images', 'nvri', true, false],
  ['naver news', 'nvrn', true, false],
  ['naver videos', 'nvrv', true, false],
  ['neosearch', 'neo', true, true],
  ['rubygems', 'rbg', true, false],
  ['peertube', 'ptb', true, false],
  ['mediathekviewweb', 'mvw', true, false],
  ['yacy', 'ya', true, false],
  ['yacy images', 'yai', true, false],
  ['rumble', 'ru', true, false],
  ['reloado', 'rel', true, false],
  ['repology', 'rep', true, true],
  ['resulthunter', 'reh', true, false],
  ['resulthunter images', 'rehi', true, false],
  ['searchch', 'sch', true, false],
  ['searchzee', 'sz', true, true],
  ['searchzee news', 'sznw', true, true],
  ['startpagina', 'spnl', true, true],
  ['startpagina images', 'spnli', true, true],
  ['startpagina videos', 'spnlv', true, true],
  ['startpagina news', 'spnln', true, true],
  ['swisscows', 'sw', true, true],
  ['swisscows images', 'swi', true, true],
  ['swisscows videos', 'swv', true, true],
  ['swisscows news', 'swn', true, true],
  ['wordnik', 'wnik', false, false],
  ['woxikon.de synonyme', 'woxi', true, false],
  ['tootfinder', 'toot', false, false],
  ['uxwing', 'ux', true, false],
  ['voidlinux', 'void', true, false],
  ['vuhuv', 'vu', true, false],
  ['vuhuv images', 'vui', true, false],
  ['vuhuv videos', 'vuv', true, false],
  ['wallhaven', 'wh', false, true],
  ['wikimini', 'wkmn', true, false],
  ['wttr.in', 'wttr', false, false],
  ['xonaly', 'xo', true, true],
  ['xprivo', 'xpr', true, true],
  ['xprivo news', 'xprn', true, true],
  ['xprivo videos', 'xprv', true, true],
  ['zapmeta', 'zpm', true, false],
  ['braveapi', null, false, true],
  ['brave', 'br', false, false],
  ['brave.images', 'brimg', false, false],
  ['brave.videos', 'brvid', false, false],
  ['brave.news', 'brnews', false, false],
  ['exaapi', 'exa', false, true],
  ['lib.rs', 'lrs', true, false],
  ['sourcehut', 'srht', true, false],
  ['bt4g', 'bt4g', false, false],
  ['pkg.go.dev', 'pgo', true, false],
  ['senscritique', 'scr', true, false],
  ['minecraft wiki', 'mcw', true, false],
  ['sina', 'sina', true, true],
  ['metacrawler', 'mec', true, true],
  ['zoo search', 'zoo', true, true],
  ['s1search', 's1', true, true]
]
