import { mkdirSync } from 'node:fs'
import { delimiter, dirname, join } from 'node:path'

import { ensureMambarc } from '../../envs'
import { getMicromambaPath } from '../../envs/paths'

/**
 * `-profile conda` on the bundled micromamba (runtime foundation §5, step 5.2).
 *
 * Each wrapper process declares `conda "${moduleDir}/environment.yml"`. Under the conda
 * profile Nextflow solves and creates those per-process environments itself, at run time.
 * That is the one intended exception to "clients install from a lock and never solve":
 * the specs belong to the vendored nf-core modules, not to Phi, and Nextflow owns their
 * cache. What Phi controls is which solver runs and where its state lives:
 *
 * - `conda.useMicromamba = true`, and the bundled micromamba is the only `micromamba`
 *   on PATH. Nextflow has no config key for the executable's path; it runs `micromamba`
 *   by name, both for `env create` and in each task's activation hook.
 * - `conda.cacheDir` is `<runtime root>/nextflow-conda`.
 * - micromamba is isolated from the user's conda exactly like Phi's own calls:
 *   `MAMBA_ROOT_PREFIX` is the runtime root, and `MAMBARC` names Phi's mambarc. Setting
 *   `MAMBARC` replaces micromamba's rc search (`micromamba config sources` then lists only
 *   that file; checked with micromamba 2.9.0), so `~/.condarc` and `~/.mambarc` are not
 *   read. Every inherited `CONDA_*` / `MAMBA_*` / `CONDARC` variable is dropped first.
 *
 * The settings go into an extra `-c` config generated per run, so no wrapper's own
 * `nextflow.config` changes.
 */

export const NEXTFLOW_CONDA_CACHE_DIR = 'nextflow-conda'

export interface CondaProfileSetup {
  /** Text of the extra `-c` config file. */
  config: string
  /** Variables to apply on top of the launch environment. */
  env: Record<string, string>
  cacheDir: string
  micromamba: string
}

export interface PreparedNextflowProfile {
  /** Complete environment for the Nextflow child. */
  env: Record<string, string>
  /** Extra Nextflow config for `-profile conda`; absent for every other profile. */
  config?: string
}

export function condaProfileSetup(
  runtimeRoot: string,
  micromamba: string = getMicromambaPath()
): CondaProfileSetup {
  const cacheDir = join(runtimeRoot, NEXTFLOW_CONDA_CACHE_DIR)
  return {
    config: renderCondaProfileConfig(cacheDir),
    env: {
      MAMBA_ROOT_PREFIX: runtimeRoot,
      MAMBARC: join(runtimeRoot, 'mambarc'),
      MAMBA_NO_BANNER: '1'
    },
    cacheDir,
    micromamba
  }
}

/** Creates the cache directory and, when absent, Phi's default mambarc. */
export function prepareCondaProfile(setup: CondaProfileSetup, runtimeRoot: string): void {
  mkdirSync(setup.cacheDir, { recursive: true })
  ensureMambarc(runtimeRoot)
}

/**
 * Applies Phi-owned runtime setup for a local Nextflow profile. Both composition and
 * plan-based runners call this so `-profile conda` cannot drift between launch paths.
 */
export function prepareNextflowProfile(
  profile: string,
  runtimeRoot: string,
  env: Record<string, string>,
  micromamba?: string
): PreparedNextflowProfile {
  if (profile !== 'conda') return { env }
  const setup = condaProfileSetup(runtimeRoot, micromamba)
  prepareCondaProfile(setup, runtimeRoot)
  return { env: withCondaProfileEnv(env, setup), config: setup.config }
}

export function renderCondaProfileConfig(cacheDir: string): string {
  return [
    '// Generated by Phi for -profile conda: per-process environments use the bundled',
    "// micromamba and Phi's runtime cache instead of the user's conda.",
    'conda {',
    '    useMicromamba = true',
    `    cacheDir = ${groovyString(cacheDir)}`,
    '}',
    ''
  ].join('\n')
}

/**
 * The launch environment for a conda-profile run: inherited conda / mamba variables
 * removed, the setup's variables applied, and the bundled micromamba's directory first
 * on PATH. Returns a new object.
 */
export function withCondaProfileEnv(
  env: Record<string, string>,
  setup: CondaProfileSetup
): Record<string, string> {
  const next: Record<string, string> = {}
  for (const [name, value] of Object.entries(env)) {
    if (isCondaVariable(name)) continue
    next[name] = value
  }
  const micromambaDir = dirname(setup.micromamba)
  const rest = (env.PATH ?? '').split(delimiter).filter((entry) => entry && entry !== micromambaDir)
  return { ...next, ...setup.env, PATH: [micromambaDir, ...rest].join(delimiter) }
}

function isCondaVariable(name: string): boolean {
  return (
    name.startsWith('CONDA_') ||
    name.startsWith('MAMBA_') ||
    name === 'CONDARC' ||
    name === 'MAMBARC' ||
    name === '_CE_CONDA' ||
    name === '_CE_M'
  )
}

function groovyString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}
