import type { RemoteHpcSettings } from '../../../../shared/wrapperRemoteTypes'
import { buildResourceConfig, type WrapperRunResources } from './resources'
import { LOG_STDERR, LOG_STDOUT } from '../executor-remote'
import { shellQuote } from '../remote-ssh-session'

/**
 * Pure builders for running a composition wrapper on an HPC login host: where
 * everything lives on the remote, the run-level Nextflow config that points
 * processes at the scheduler, and the launch script. No I/O, so all of it is
 * unit-testable and none of it needs a cluster.
 */

export interface RemoteRunLayout {
  /** `<root>/wrappers/runs/<runId>`: params, config, launch script, logs, work dir and results. */
  runDir: string
  /** `<root>/wrappers/bundles/<hash>`: the shipped wrapper source tree, shared by every run of that version. */
  bundleDir: string
  /** The wrapper's own component inside the bundle; Nextflow starts here, like the local runner does. */
  componentDir: string
  paramsFile: string
  configFile: string
  workDir: string
  /** Default `outdir` for the run when the caller did not choose one. */
  outDir: string
}

function trimTrailingSlashes(path: string): string {
  return path.replace(/\/+$/, '')
}

/** All remote paths are POSIX, whatever OS Phi itself runs on. */
export function remoteRunLayout(input: {
  workspaceRoot: string
  runId: string
  bundleHash: string
  componentRelPath: string
}): RemoteRunLayout {
  const root = trimTrailingSlashes(input.workspaceRoot)
  const runDir = `${root}/wrappers/runs/${input.runId}`
  const bundleDir = `${root}/wrappers/bundles/${input.bundleHash}`
  return {
    runDir,
    bundleDir,
    componentDir: `${bundleDir}/${input.componentRelPath}`,
    paramsFile: `${runDir}/params.json`,
    configFile: `${runDir}/phi_remote.config`,
    workDir: `${runDir}/work`,
    outDir: `${runDir}/results`
  }
}

/** A relative outdir is anchored in the run directory; an absolute one is the caller's choice. */
export function resolveRemoteOutDir(outdir: unknown, runDir: string): string {
  if (typeof outdir !== 'string' || outdir === '') return `${runDir}/results`
  return outdir.startsWith('/') ? outdir : `${runDir}/${outdir}`
}

/** A Groovy single-quoted string literal. */
function groovyString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/**
 * The run-level config passed with `-c`. It outranks the wrapper's own
 * nextflow.config, so it decides *where* tasks run without touching the
 * wrappers themselves (which only know docker/singularity/conda).
 */
export function buildRemoteNextflowConfig(
  hpc: RemoteHpcSettings,
  resources?: WrapperRunResources
): string {
  const lines = [
    '// Generated by Phi for this run. Do not edit.',
    `process.executor = ${groovyString(hpc.scheduler === 'slurm' ? 'slurm' : 'local')}`
  ]
  if (hpc.scheduler === 'slurm') {
    if (hpc.queue) lines.push(`process.queue = ${groovyString(hpc.queue)}`)
    const options = [hpc.account ? `--account=${hpc.account}` : '', hpc.clusterOptions ?? '']
      .map((part) => part.trim())
      .filter(Boolean)
      .join(' ')
    if (options) lines.push(`process.clusterOptions = ${groovyString(options)}`)
    if (hpc.queueSize && hpc.queueSize > 0) {
      lines.push(`executor.queueSize = ${Math.floor(hpc.queueSize)}`)
    }
  }
  if (hpc.singularityCacheDir) {
    lines.push(`singularity.cacheDir = ${groovyString(hpc.singularityCacheDir)}`)
  }
  const siteConfig = hpc.nextflowConfig?.trim()
    ? `// Site settings from the connection.\n${hpc.nextflowConfig.trim()}\n`
    : ''
  const resourceConfig = buildResourceConfig(resources)
  return `${lines.join('\n')}\n${siteConfig}${resourceConfig}`
}

/**
 * SSH runs commands in a non-login shell, where `module` (defined by /etc/profile) and any PATH
 * the user sets in their profile are missing. Load them the way a login would, tolerating a
 * profile that fails or does not exist, and before errexit is switched on.
 */
const LOGIN_ENVIRONMENT = [
  '  [ -f /etc/profile ] && . /etc/profile >/dev/null 2>&1 || true',
  '  for f in "$HOME/.bash_profile" "$HOME/.profile"; do',
  '    if [ -f "$f" ]; then . "$f" >/dev/null 2>&1 || true; break; fi',
  '  done'
]

/**
 * `launch.sh`: setup lines, then Nextflow from the component dir. The steps run in
 * a `set -e` subshell so a failed `module load` stops the launch, and the exit code
 * is recorded either way (Phi's status polling reads that file).
 */
export function buildRemoteLaunchScript(input: {
  layout: RemoteRunLayout
  profile: string
  hpc: RemoteHpcSettings | undefined
}): string {
  const { layout, profile, hpc } = input
  const setup = (hpc?.setupCommands ?? []).map((line) => line.trim()).filter(Boolean)
  const nextflow = [
    hpc?.nextflowBin || 'nextflow',
    'run',
    'wrapper/main.nf',
    '-params-file',
    layout.paramsFile,
    '-profile',
    profile,
    '-c',
    layout.configFile,
    '-w',
    layout.workDir
  ]
    .map(shellQuote)
    .join(' ')
  return buildRemoteConfiguredLaunchScript({
    runDir: layout.runDir,
    commands: [`cd ${shellQuote(layout.componentDir)}`, nextflow],
    setupCommands: setup
  })
}

/** Shared by composition and legacy runners so saved setup executes in the actual head job. */
export function buildRemoteConfiguredLaunchScript(input: {
  runDir: string
  commands: string[]
  setupCommands?: string[]
}): string {
  const body = [
    '(',
    ...LOGIN_ENVIRONMENT,
    '  set -e',
    ...(input.setupCommands ?? [])
      .map((line) => line.trim())
      .filter(Boolean)
      .map((line) => `  ${line}`),
    '  export NXF_ANSI_LOG=false',
    // The launcher otherwise curls nextflow.io for a newer version before every run,
    // with no timeout of its own: minutes of silence on a slow or offline host.
    '  export NXF_DISABLE_CHECK_LATEST=true',
    ...input.commands.map((line) => `  ${line}`),
    ')'
  ].join('\n')
  // Record the exit code, then exit with it: under `sbatch` the job's own state is the
  // scheduler's answer, and it must say FAILED when Nextflow failed.
  const trap = ['rc=$?', `echo "$rc" > ${shellQuote('exit_code')}`, 'exit "$rc"'].join('\n')
  return `#!/usr/bin/env bash\ncd ${shellQuote(input.runDir)}\n${body}\n${trap}\n`
}

/** Slurm job names: keep to characters that survive being parsed back out of `squeue`. */
function slurmJobName(runId: string): string {
  return `phi-${runId.replace(/[^a-zA-Z0-9_-]/g, '-')}`
}

/**
 * Splits free-text sbatch flags into one flag per `#SBATCH` line. A bare value after a flag
 * (`--time 7-00:00:00`) is joined with `=`; anything before the first flag is dropped. Whitespace,
 * including newlines, only ever separates flags: nothing here can add a line that is not a directive.
 */
export function sbatchFlags(text: string | undefined): string[] {
  const flags: string[] = []
  for (const token of (text ?? '').split(/\s+/).filter(Boolean)) {
    if (token.startsWith('-')) flags.push(token)
    else if (flags.length > 0 && !flags[flags.length - 1].includes('=')) {
      flags[flags.length - 1] = `${flags[flags.length - 1]}=${token}`
    }
  }
  return flags
}

/**
 * `job.sbatch` for the `sbatch` controller: the Nextflow head process as a Slurm job of its own.
 * Logs go to the same files the login-node controller writes, so Phi reads both the same way.
 * The default time limit is long on purpose: the partition default (often an hour or two) would
 * silently kill a pipeline that is still running; `controllerOptions` overrides any default here.
 */
export function buildRemoteSbatchScript(input: {
  layout: RemoteRunLayout
  runId: string
  hpc: RemoteHpcSettings | undefined
}): string {
  const { layout, runId, hpc } = input
  const slurm = hpc?.scheduler === 'slurm'
  const directives = [
    `--job-name=${slurmJobName(runId)}`,
    `--chdir=${layout.runDir}`,
    `--output=${layout.runDir}/${LOG_STDOUT}`,
    `--error=${layout.runDir}/${LOG_STDERR}`,
    ...(slurm ? ['--cpus-per-task=1', '--mem=4G'] : []),
    '--time=2-00:00:00',
    ...(hpc?.queue ? [`--partition=${hpc.queue}`] : []),
    ...(hpc?.account ? [`--account=${hpc.account}`] : []),
    ...sbatchFlags(hpc?.controllerOptions)
  ]
  return [
    '#!/bin/bash',
    ...directives.map((flag) => `#SBATCH ${flag}`),
    '',
    'bash launch.sh',
    ''
  ].join('\n')
}

/**
 * Run over SSH before anything is uploaded or launched. Missing Nextflow or `sbatch` makes
 * the run impossible, so those fail with the setting to change; a missing container runtime
 * only warns, since some sites provide it on the compute nodes only.
 */
export function buildRemotePreflightScript(input: {
  hpc: RemoteHpcSettings | undefined
  profile: string
  workspaceRoot?: string
}): string {
  const { hpc, profile, workspaceRoot } = input
  const batchHead = hpc?.controller === 'sbatch'
  const setup = (batchHead ? [] : (hpc?.setupCommands ?? []))
    .map((line) => line.trim())
    .filter(Boolean)
  const {
    nextflow,
    requiresSbatch,
    runtimeCandidates: wanted
  } = remotePreflightRequirements(hpc, profile)
  const lines = [
    '#!/usr/bin/env bash',
    ...LOGIN_ENVIRONMENT.map((line) => line.trimStart()),
    'set -e',
    ...setup,
    ...(workspaceRoot
      ? [
          `if ! { test -d ${shellQuote(workspaceRoot)} && test -r ${shellQuote(workspaceRoot)} && test -w ${shellQuote(workspaceRoot)} && test -x ${shellQuote(workspaceRoot)}; }; then`,
          `  echo ${shellQuote(`服务器工作目录不存在或没有读取、写入与进入权限: ${workspaceRoot}`)} >&2`,
          '  exit 1',
          'fi'
        ]
      : []),
    `if ! command -v ${shellQuote(nextflow)} >/dev/null 2>&1; then`,
    batchHead
      ? `  echo ${shellQuote('WARN: 登录节点未找到 Nextflow；请确认 sbatch 计算节点的启动命令会提供它。')}`
      : `  echo ${shellQuote(`Nextflow was not found on the host ("${nextflow}"). Set the Nextflow path in the connection settings, or add a setup command such as "module load nextflow".`)} >&2`,
    ...(batchHead ? [] : ['  exit 1']),
    'fi',
    'if ! command -v java >/dev/null 2>&1; then',
    batchHead
      ? `  echo ${shellQuote('WARN: 登录节点未找到 Java；请确认 sbatch 计算节点的启动命令会提供它。')}`
      : `  echo ${shellQuote('Java 未在服务器运行环境中找到；请配置 Java 或在启动命令中加载。')} >&2`,
    ...(batchHead ? [] : ['  exit 1']),
    'fi'
  ]
  if (hpc?.controller === 'sbatch' && hpc.scheduler !== 'slurm') {
    lines.push(
      `echo ${shellQuote('sbatch 控制方式必须同时选择 Slurm 调度，已拒绝在登录节点执行。')} >&2`,
      'exit 1'
    )
  }
  if (requiresSbatch) {
    for (const command of ['sbatch', 'squeue', 'scontrol', 'scancel']) {
      lines.push(
        `if ! command -v ${command} >/dev/null 2>&1; then`,
        `  echo ${shellQuote(`${command} 未在服务器运行环境中找到；当前配置选择了 Slurm，不会自动改为主机本地执行。`)} >&2`,
        '  exit 1',
        'fi'
      )
    }
  }
  if (wanted.length > 0) {
    const anyPresent = wanted.map((tool) => `command -v ${tool} >/dev/null 2>&1`).join(' || ')
    lines.push(
      `if ! { ${anyPresent}; }; then`,
      hpc?.scheduler === 'slurm'
        ? `  echo ${shellQuote(`WARN: ${wanted.join(' / ')} 在登录节点未找到；请确认计算节点可运行所选 ${profile} profile。`)}`
        : `  echo ${shellQuote(`${wanted.join(' / ')} 在主机上不可用，无法直接运行所选 ${profile} profile。`)} >&2`,
      ...(hpc?.scheduler === 'slurm' ? [] : ['  exit 1']),
      'fi'
    )
  }
  if (hpc?.scheduler === 'slurm' && hpc.controller !== 'sbatch') {
    lines.push(
      `echo ${shellQuote('WARN: Nextflow 控制进程将在登录节点持续运行；若集群禁止，请选择 sbatch 控制方式。')}`
    )
  }
  return `${lines.join('\n')}\n`
}

/** Shared tool selection for launch preflight and the read-only remote doctor. */
export function remotePreflightRequirements(
  hpc: RemoteHpcSettings | undefined,
  profile: string
): { nextflow: string; requiresSbatch: boolean; runtimeCandidates: string[] } {
  const runtimeTool: Record<string, string[]> = {
    singularity: ['singularity', 'apptainer'],
    docker: ['docker'],
    conda: ['conda', 'mamba']
  }
  return {
    nextflow: hpc?.nextflowBin || 'nextflow',
    requiresSbatch: hpc?.scheduler === 'slurm' || hpc?.controller === 'sbatch',
    runtimeCandidates: runtimeTool[profile] ?? []
  }
}
